apiVersion: v1
kind: Service
metadata:
  name: {{ template "locust.coordinator-service-api" . }}
  labels:
    {{- include "locust.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.locust.locustPort }}
      targetPort: {{ .Values.locust.locustPort }}
      protocol: TCP
{{/*      name: external-locust-coordinator-port*/}}
  selector:
    {{- include "locust.selectorLabels" . | nindent 4 }}
